--CREACION DE LAS TABLAS DEL UNIVERSO DEL DISCURSO

--CREACION DE LA TABLA PAIS
CREATE TABLE PAIS (
  ID_PAIS INT NOT NULL,
  NOMBRE VARCHAR2(80) NOT NULL,
  PRIMARY KEY(ID_PAIS)
);
--CREACION DE LA TABLA PRESENTACION
CREATE TABLE PRESENTACION (
  ID_PRESENTACION INT NOT NULL,
  NOMBRE VARCHAR2(80) NOT NULL,
  PRIMARY KEY(ID_PRESENTACION)
);
--CREACION DE LA TABLA MARCA
CREATE TABLE MARCA (
  ID_MARCA INT NOT NULL,
  NOMBRE VARCHAR2(80) NOT NULL,
  PRIMARY KEY(ID_MARCA)
);
--CREACION DE LA TABLA CLASIFICACION DEL PRODUCTO
CREATE TABLE CLASIFICACION_PRODUCTO (
  ID_CLASIFICACION_PRODUCTO INT NOT NULL,
  NOMBRE VARCHAR2(50) NOT NULL,
  PRIMARY KEY(ID_CLASIFICACION_PRODUCTO)
);
--CREACION DE LA TABLA PROVEEDOR
CREATE TABLE PROVEEDOR (
  ID_PROVEEDOR INT NOT NULL,
  NIT VARCHAR2(30) NOT NULL,
  RAZON_SOCIAL VARCHAR2(50) NOT NULL,
  TELEFONO_FIJO VARCHAR2(12) NOT NULL,
  CELULAR VARCHAR2(20) NOT NULL,
  DIRECCION VARCHAR2(60),
  CORREO VARCHAR2(80) NOT NULL,
  PRIMARY KEY(ID_PROVEEDOR)
);
--CREACION DE LA TABLA EPS
CREATE TABLE EPS (
  ID_EPS INT NOT NULL,
  NOMBRE VARCHAR2(80) NOT NULL,
  PRIMARY KEY(ID_EPS)
);
--CREACION DE LA TABLA SUCURSAL
CREATE TABLE SUCURSAL (
  ID_SUCURSAL INT NOT NULL,
  NOMBRE VARCHAR2(30) NOT NULL,
  NIT VARCHAR2(40) NOT NULL,
  DIRECCION VARCHAR2(80) NOT NULL,
  TELEFONO_FIJO VARCHAR2(12) NOT NULL,
  CELULAR VARCHAR2(15) NOT NULL,
  CORREO VARCHAR2(80) NOT NULL,
  RED_INSTAGRAM VARCHAR2(80),
  RED_META VARCHAR2(80),
  PRIMARY KEY(ID_SUCURSAL)
);
--CREACION DE LA TABLA CARGO
CREATE TABLE CARGO (
  ID_CARGO INT NOT NULL,
  DESCRIPCION VARCHAR2(100) NOT NULL,
  PRIMARY KEY(ID_CARGO)
);
--CREACION DE LA TABLA NACIONALIDAD
CREATE TABLE NACIONALIDAD (
  ID_NACIONALIDAD INT NOT NULL,
  NOMBRE VARCHAR2(80) NOT NULL,
  PRIMARY KEY(ID_NACIONALIDAD)
);
--CREACION DE LA TABLA MUNICIPIO
CREATE TABLE MUNICIPIO (
  ID_MUNICIPIO INT NOT NULL,
  NOMBRE VARCHAR2(80) NOT NULL,
  PRIMARY KEY(ID_MUNICIPIO)
);
--CREACION DE LA TABLA TIPO_DOCUMENTO
CREATE TABLE TIPO_DOCUMENTO (
  ID_TIPO_DOCUMENTO INT NOT NULL,
  NOMBRE VARCHAR2(50) NOT NULL,
  PRIMARY KEY(ID_TIPO_DOCUMENTO)
);
--CREACION DE LA TABLA CLIENTE
CREATE TABLE CLIENTE (
  ID_CLIENTE INT NOT NULL,
  IDENTIFICACION VARCHAR2(20) NOT NULL,
  PRIMER_NOMBRE VARCHAR2(30) NOT NULL,
  SEGUNDO_NOMBRE VARCHAR2(30),
  PRIMER_APELLIDO VARCHAR2(40) NOT NULL,
  SEGUNDO_APELLIDO VARCHAR2(40) NOT NULL,
  TELEFONO_FIJO VARCHAR2(12),
  CELULAR VARCHAR2(15) NOT NULL,
  FECHA_NACIMIENTO DATE,
  LUGAR_TRABAJO VARCHAR2(60),
  ANTIGUEDAD_TRABAJO INTEGER,
  DIRECCION_CASA VARCHAR2(60),
  CORREO VARCHAR2(60) NOT NULL,
  CUPO_CREDITO NUMBER(6,2),
  ID_TIPO_DOCUMENTO INT NOT NULL,
  ID_MUNICIPIO INT NOT NULL,
  PRIMARY KEY(ID_CLIENTE),
  FOREIGN KEY(ID_TIPO_DOCUMENTO) REFERENCES TIPO_DOCUMENTO(ID_TIPO_DOCUMENTO),
  FOREIGN KEY(ID_MUNICIPIO) REFERENCES MUNICIPIO(ID_MUNICIPIO)
);
--CREACION DE LA TABLA PRODUCTO
CREATE TABLE PRODUCTO (
  ID_PRODUCTO INT NOT NULL,
  CODIGO VARCHAR2(15) NOT NULL,
  DESCRIPCION VARCHAR2(80) NOT NULL,
  COSTO NUMBER(10,5) NOT NULL,
  PRECIO_VENTA NUMBER(10,5) NOT NULL,
  IVA NUMBER(10,5) NOT NULL,
  ICO NUMBER(10,5) NOT NULL,
  PRECIO_BASE NUMBER(10,5) NOT NULL,
  MARGEN_CONTRIBUCION NUMBER(10,5) NOT NULL,
  DESCUENTO NUMBER(3,2),
  EXISTENCIA INTEGER NOT NULL,
  ID_PRESENTACION INT NOT NULL,
  ID_PAIS INT NOT NULL,
  ID_MARCA INT NOT NULL,
  ID_CLASIFICACION_PRODUCTO INT NOT NULL,
  PRIMARY KEY(ID_PRODUCTO),
  FOREIGN KEY(ID_PRESENTACION) REFERENCES PRESENTACION(ID_PRESENTACION),
  FOREIGN KEY(ID_PAIS) REFERENCES PAIS(ID_PAIS),
  FOREIGN KEY(ID_MARCA) REFERENCES MARCA(ID_MARCA),
  FOREIGN KEY(ID_CLASIFICACION_PRODUCTO) REFERENCES CLASIFICACION_PRODUCTO(ID_CLASIFICACION_PRODUCTO)
);
--CREACION DE LA TABLA EMPLEADO
CREATE TABLE EMPLEADO (
  ID_EMPLEADO INT NOT NULL,
  IDENTIFICACION VARCHAR2(20) NOT NULL,
  PRIMER_NOMBRE VARCHAR2(30) NOT NULL,
  SEGUNDO_NOMBRE VARCHAR2(30),
  PRIMER_APELLIDO VARCHAR2(40) NOT NULL,
  SEGUNDO_APELLIDO VARCHAR2(40) NOT NULL,
  TELEFONO_FIJO VARCHAR2(12),
  CELULAR VARCHAR2(15) NOT NULL,
  DIRECCION VARCHAR2(60) NOT NULL,
  FECHA_NACIMIENTO DATE NOT NULL,
  SALARIO NUMBER(7,4) NOT NULL,
  FECHA_INGRESO DATE NOT NULL,
  GENERO VARCHAR2(20),
  ID_CARGO INT NOT NULL,
  ID_SUCURSAL INT NOT NULL,
  ID_NACIONALIDAD INT NOT NULL,
  ID_EPS INT NOT NULL,
  ID_TIPO_DOCUMENTO INT NOT NULL,
  PRIMARY KEY(ID_EMPLEADO),
  FOREIGN KEY (ID_CARGO) REFERENCES CARGO(ID_CARGO),
  FOREIGN KEY(ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL),
  FOREIGN KEY(ID_NACIONALIDAD) REFERENCES NACIONALIDAD(ID_NACIONALIDAD),
  FOREIGN KEY(ID_EPS) REFERENCES EPS(ID_EPS),
  FOREIGN KEY(ID_TIPO_DOCUMENTO) REFERENCES TIPO_DOCUMENTO(ID_TIPO_DOCUMENTO)
);
--CREACION DE LA TABLA PEDIDO
CREATE TABLE PEDIDO(
  ID_PEDIDO INT NOT NULL,
  FECHA_SOLICITUD DATE NOT NULL,
  NUMERO VARCHAR2(40) NOT NULL,
  FECHA_ENTREGA DATE,
  VALOR NUMBER(10,5) NOT NULL,
  ID_PROVEEDOR INT NOT NULL,
  ID_PRODUCTO INT NOT NULL,
  ID_EMPLEADO INT NOT NULL,
  PRIMARY KEY (ID_PEDIDO),
  FOREIGN KEY(ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR),
  FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
  FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO)
);
--CREACION DE LA TABLA TIPO DE VENTA
CREATE TABLE TIPO_VENTA(
  ID_TIPO_VENTA INT NOT NULL,
  DESCRIPCION VARCHAR2(2) NOT NULL,
  PRIMARY KEY (ID_TIPO_VENTA)
);
--CREACION DE LA TABLA VENTA
CREATE TABLE VENTA (
  ID_VENTA INT NOT NULL,
  FECHA DATE NOT NULL,
  TOTAL_DESCUENTO NUMBER(10,5),
  TOTAL_IVA NUMBER(10,5) NOT NULL,
  TOTAL_ICO NUMBER (10,5) NOT NULL,
  TOTAL_VENTA NUMBER(10,5) NOT NULL,
  ID_EMPLEADO INT NOT NULL,
  ID_TIPO_VENTA INT NOT NULL,
  ID_CLIENTE INT NOT NULL,
  PRIMARY KEY(ID_VENTA),
  FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO),
  FOREIGN KEY(ID_TIPO_VENTA) REFERENCES TIPO_VENTA(ID_TIPO_VENTA),
  FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);
--CREACION DE LA TABLA CUENTA POR COBRAR
CREATE TABLE CUENTA_COBRAR(
  ID_CUENTA_COBRAR INT NOT NULL,
  DESCRIPCION VARCHAR2(100),
  FECHA_INICIAL DATE NOT NULL,
  FECHA_LIMITE DATE NOT NULL,
  VALOR_INICIAL NUMBER(10,5) NOT NULL,
  VALOR_PENDIENTE NUMBER(10,5) NOT NULL,
  ID_TIPO_VENTA INT NOT NULL,
  PRIMARY KEY(ID_CUENTA_COBRAR),
  FOREIGN KEY(ID_TIPO_VENTA) REFERENCES TIPO_VENTA(ID_TIPO_VENTA)
);
--CREACION DE LA TABLA ABONO
CREATE TABLE ABONO(
  ID_ABONO INT NOT NULL,
  DESCRIPCION VARCHAR2(100),
  FECHA DATE NOT NULL,
  VALOR NUMBER(10,5) NOT NULL,
  ID_CUENTA_COBRAR INT NOT NULL,
  PRIMARY KEY(ID_ABONO),
  FOREIGN KEY(ID_CUENTA_COBRAR) REFERENCES CUENTA_COBRAR(ID_CUENTA_COBRAR)
);
--CREACION DE LA TABLA DETALLE DE LA VENTA
CREATE TABLE DETALLE_VENTA (
  ID_DETALLE_VENTA INT NOT NULL,
  ID_PRODUCTO INT NOT NULL,
  CANTIDAD INTEGER NOT NULL,
  ID_VENTA INT NOT NULL,
  PRIMARY KEY(ID_DETALLE_VENTA),
  FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
  FOREIGN KEY(ID_VENTA) REFERENCES VENTA(ID_VENTA)
);

-- DROP DE LAS TABLAS
/*
DROP TABLE DETALLE_VENTA;
DROP TABLE ABONO;
DROP TABLE CUENTA_COBRAR;
DROP TABLE VENTA;
DROP TABLE TIPO_VENTA;
DROP TABLE PEDIDO;
DROP TABLE EMPLEADO;
DROP TABLE PRODUCTO;
DROP TABLE CLIENTE;
DROP TABLE TIPO_DOCUMENTO;
DROP TABLE MUNICIPIO;
DROP TABLE NACIONALIDAD;
DROP TABLE CARGO;
DROP TABLE SUCURSAL;
DROP TABLE EPS;
DROP TABLE PROVEEDOR;
DROP TABLE CLASIFICACION_PRODUCTO;
DROP TABLE MARCA;
DROP TABLE PRESENTACION;
DROP TABLE PAIS;
*/






